name: eiu-pchem-env
channels:
  - conda-forge
  - psi4
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - partd
  - scikit-learn
  - openpyxl
  - psi4
  - fortecubeview
  - ase
  - psi4-rt
  - conda-forge/label/libint_dev::libint
  - dftd3-python
