name: eiu-pchem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - partd
  - scikit-learn
  - openpyxl
  - psi4=1.10
  - fortecubeview
  - dftd3-python
  - lammps
  - mpi4py
  - rdkit
  - plotly
  - py3Dmol
  - ase
  - pip:
    - AaronTools
