name: eiu-pchem-env
channels:
  - conda-forge
  - veloxchem
  - tbmasood
dependencies:
  - python>=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - partd
  - scikit-learn
  - openpyxl
  - scipy
  - seaborn
  - fortecubeview
  - dftd3-python
  - lammps
  - openkim-models
  - mpi4py
  - rdkit
  - plotly
  - py3Dmol
  - webcolors
  - jsonschema-with-format-nongpl
  - black
  - isort
  - ghp-import
  - k3d
  - ipympl
  - ipywidgets
  - openmm
  - veloxchem
  - multipsi
  - dftd4-python
  - xtb-python
  - valet
  - adcc
  - pip
  - pip:
    - ase
    - git+https://github.com/gator-program/respondo.git@v0.0.5
    - git+https://github.com/gator-program/gator.git@vlx-newints
