name: eiu-pchem-env
channels:
  - conda-forge
  - psi4
  - defaults
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - partd
  - scikit-learn
  - openpyxl
  - psi4
  - fortecubeview
  - ase
  - psi4-rt
  
