name: eiu-pchem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - partd
  - scikit-learn
  - openpyxl
  - scipy
  - seaborn
  - fortecubeview
  - dftd4-python
  - lammps
  - openkim-models
  - mpi4py
  - rdkit
  - plotly
  - py3Dmol
  - ase
